easy_admin:

    site_name: "StuRa Finanzen"

    design:
      menu:
        - { entity: 'PaymentOrder', icon: 'bank', label: 'payment_order.labelp' }
        - { entity: 'Department', icon: 'sitemap', label: 'department.labelp' }
        - { entity: 'User', icon: 'user', label: 'user.labelp' }

    entities:

        User:
          class: App\Entity\User
          label: 'user.label'
          controller: App\Controller\UserAdminController

          list:
            fields:
              - property: 'id'
                label: 'user.id.label'
              - property: 'username'
                label: 'user.username.label'
              - property: 'fullName'
                label: 'user.fullName.label'
              - property: 'role_description'
                label: 'user.role_description.label'
              - property: 'email'
                type: 'email'
                label: 'user.email.label'

          form:
            fields:
              - property: 'username'
                label: 'user.username.label'
              - property: 'first_name'
                label: 'user.first_name.label'
                type_options:
                  required: false
                  empty_data: ''
              - property: 'last_name'
                label: 'user.last_name.label'
                type_options:
                  required: false
                  empty_data: ''
              - property: 'email'
                label: 'user.email.label'
                type_options:
                  required: false
                  empty_data: ''
              - property: 'role_description'
                label: 'user.role_description.label'
                type_options:
                  required: false
                  empty_data: ''

              - { type: 'section', label: 'user.section.password', help: 'user.section.password.help' }
              - property: 'plain_password'
                type: 'repeated'
                type_options:
                  type: 'Symfony\Component\Form\Extension\Core\Type\PasswordType'
                  required: false
                  first_options: { label: 'password.new' }
                  second_options: { label: 'password.repeat' }

        PaymentOrder:
            class: App\Entity\PaymentOrder
            label: 'payment_order.label'

            list:
              fields:
                - property: 'id'
                  label: 'payment_order.id.label'
                - property: 'project_name'
                  label: 'payment_order.project_name.label'
                - property: 'department.name'
                  label: 'payment_order.department.label'
                - property: 'amount'
                  label: 'payment_order.amount.label'
                  template: 'admin/payment_order/field_money.html.twig'

                - property: 'mathematically_correct'
                  label: 'payment_order.mathematically_correct.label'
                  help: 'payment_order.mathematically_correct.help'

                - property: 'factually_correct'
                  label: 'payment_order.factually_correct.label'
                  help: 'payment_order.factually_correct.help'

                - property: 'creation_date'

            form:
              fields:
                - { type: 'tab' , label: 'payment_order.tab.basic' }

                - { type: 'group', columns: 8, label: 'payment_order.group.info' }
                - property: 'first_name'
                  label: 'payment_order.first_name.label'
                  type_options:
                    attr:
                      placeholder: 'payment_order.first_name.placeholder'

                - property: 'last_name'
                  label: 'payment_order.last_name.label'
                  type_options:
                    attr:
                     placeholder: 'payment_order.last_name.placeholder'

                - property: 'department'
                  label: 'payment_order.department.label'
                  type: 'entity'
                  type_options:
                    attr:
                     placeholder: 'select.choose_value'

                - property: 'amount'
                  label: 'payment_order.amount.label'
                  type: 'money'
                  type_options:
                    divisor: 100
                    currency: 'EUR'
                    attr:
                      placeholder: 'payment_order.amount.placeholder'

                - property: 'project_name'
                  label: 'payment_order.project_name.label'
                  type_options:
                    attr:
                      placeholder: 'payment_order.project_name.placeholder'

                - { type: 'group', columns: 4, label: 'payment_order.group.status' }
                - property: 'mathematically_correct'
                  label: 'payment_order.mathematically_correct.label'
                  help: 'payment_order.mathematically_correct.help'

                - property: 'factually_correct'
                  label: 'payment_order.factually_correct.label'
                  help: 'payment_order.factually_correct.help'

                - { type: 'tab' , label: 'payment_order.tab.bank_account' }

                - { type: 'group', columns: 6, label: 'payment_order.group.receiver' }
                - property: 'bank_info.account_owner'
                  label: 'bank_info.account_owner.label'
                  type_options:
                    attr:
                      placeholder: 'bank_info.account_owner.placeholder'

                - property: 'bank_info.street'
                  label: 'bank_info.street.label'
                  type_options:
                    attr:
                      placeholder: 'bank_info.street.placeholder'

                - property: 'bank_info.zip_code'
                  label: 'bank_info.zip_code.label'
                  type_options:
                    attr:
                      placeholder: 'bank_info.zip_code.placeholder'

                - property: 'bank_info.city'
                  label: 'bank_info.city.label'
                  type_options:
                    attr:
                      placeholder: 'bank_info.city.placeholder'

                - { type: 'group', columns: 6, label: 'payment_order.group.bank_info' }
                - property: 'bank_info.iban'
                  label: 'bank_info.iban.label'
                  type_options:
                    attr:
                      placeholder: 'bank_info.iban.placeholder'

                - property: 'bank_info.bic'
                  label: 'bank_info.bic.label'
                  type_options:
                    attr:
                      placeholder: 'bank_info.bic.placeholder'

                - property: 'bank_info.bank_name'
                  label: 'bank_info.bank_name.label'
                  type_options:
                    attr:
                      placeholder: 'bank_info.bank_name.placeholder'

                - property: 'bank_info.reference'
                  label: 'bank_info.reference.label'
                  type_options:
                    required: false
                    attr:
                      placeholder: 'bank_info.reference.placeholder'

        Department:
            class: App\Entity\Department
            label: 'department.label'
            help: 'department.help'
            list:
                fields:
                    - property: 'id'
                      label: 'department.id.label'
                    - property: 'name'
                      label: 'department.name.label'
                    - property: 'type'
                      label: 'department.type.label'
                      template: 'admin/department/field_choice.html.twig'
                    - property: 'blocked'
                      label: 'department.blocked.label'
                    - property: 'last_modified'

            form:
                fields:
                    - property: 'name'
                      label: 'department.name.label'
                    - property: 'type'
                      label: 'department.type.label'
                      type: 'choice'
                      type_options:
                        choices:
                            'department.type.fsr': 'fsr'
                            'department.type.section': 'section'
                            'department.type.misc': 'misc'
                    - property: 'blocked'
                      label: 'department.blocked.label'
                      help: 'department.blocked.help'
                    - property: 'last_modified'
                      type_options:
                        disabled: true
                    - property: 'creation_date'
                      type_options:
                        disabled: true



#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\User
