framework:
  rate_limiter:
    payment_order_submit:
      # use 'sliding_window' if you prefer that policy
      policy: 'fixed_window'
      limit: 30
      interval: '60 minutes'

    funding_application_submit:
      policy: 'fixed_window'
      limit: 30
      interval: '60 minutes'