security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            logout:
                path: app_logout
            guard:
                authenticators:
                    - App\Security\FormLoginAuthenticator

            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check



            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_VIEW_AUDITS: [ROLE_ADMIN]
        ROLE_EDIT_USER: [ROLE_ADMIN, ROLE_READ_USER]
        ROLE_EDIT_ORGANISATIONS: [ROLE_ADMIN, ROLE_READ_BANK_ACCOUNTS, ROLE_READ_ORGANISATIONS]
        ROLE_SHOW_PAYMENT_ORDERS: [ROLE_ADMIN, ROLE_READ_BANK_ACCOUNTS, ROLE_READ_ORGANISATIONS]
        ROLE_EDIT_PAYMENT_ORDERS: [ROLE_SHOW_PAYMENT_ORDERS, ROLE_EXPORT_PAYMENT_ORDERS]
        ROLE_EXPORT_REFERENCES: [ROLE_EXPORT_PAYMENT_ORDERS_REFERENCES, ROLE_SHOW_PAYMENT_ORDERS]
        ROLE_PO_FACTUALLY: ROLE_EDIT_PAYMENT_ORDERS
        ROLE_PO_MATHEMATICALLY: ROLE_EDIT_PAYMENT_ORDERS
        ROLE_EDIT_BANK_ACCOUNTS: ROLE_ADMIN
        ROLE_MANUAL_CONFIRMATION: ROLE_ADMIN

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # This makes the logout route accessible during two-factor authentication. Allows the user to
        # cancel two-factor authentication, if they need to.
        - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # This ensures that the form can only be accessed when two-factor authentication is in progress.
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }


        - { path: ^/admin/audit, roles: ROLE_VIEW_AUDITS}
        - { path: ^/admin/user/settings, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }

