vich_uploader:
    db_driver: orm
    storage: '@App\Services\Upload\ExtendedFileSystemStorage'

    mappings:
        payment_orders_form:
            #uri_prefix: /uploads/payment_orders/forms
            #upload_destination: '%kernel.project_dir%/public/uploads/payment_orders/forms'
            upload_destination: '%kernel.project_dir%/uploads/payment_orders/forms'
            namer:  App\Services\Upload\PaymentOrderFileNamer

            inject_on_load: true

        payment_orders_references:
            #uri_prefix: /uploads/payment_orders/references
            #upload_destination: '%kernel.project_dir%/public/uploads/payment_orders/references'
            upload_destination: '%kernel.project_dir%/uploads/payment_orders/references'
            namer:  App\Services\Upload\PaymentOrderFileNamer

            inject_on_load: true

        funding_application_explanation:
            upload_destination: '%kernel.project_dir%/uploads/funding_application/explanations'
            #namer: App\Services\Upload\PaymentOrderFileNamer
            inject_on_load: true

        funding_application_finance_plan:
            upload_destination: '%kernel.project_dir%/uploads/funding_application/finance_plans'
            #namer: App\Services\Upload\PaymentOrderFileNamer
            inject_on_load: true
