controllers:
    resource: '../../src/Controller/'
    #exclude: '../../src/Controller/Admin/*'
    type: attribute
    prefix:
        de: ''
        de_DE: '/de'
        en: '/en'

#controllers_admin:
#    resource: ../../src/Controller/Admin
#    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: attribute
